# Generated by Django 4.1.1 on 2022-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
